### ISSUE TITLE
Add a "close" button to remove facet displays from grid

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/data-explorer#291]
I did a search in the facet search bar and picked a new facet.
It wasn't the right one.
I am not able to remove the facet display from the grid.
I needed to reload data explorer to make it go away.

It would be great if I had a way to remove the facet (an X in one of the upper corners).

**Comment by wnojopra** [comment]
We wanted to prioritize adding [query parameters](https://github.com/DataBiosphere/data-explorer/issues/311), but realized that would remove the ability to reload the page to make extra facets go away. I'm now thinking having a way to remove extra facet cards is blocking adding query parameters.

**Comment by melissachang** [comment]
Matt, here is our plan:
- There will be an "x" in upper right, to close the card
- We will only show an "x" for the new facets. Ideally we would show "x" for every card, but that would be significantly more engineering work
- Instead of showing "x" all the time, anytime you hover in the card, the number on upper right will change to "x". If we showed "x" all the time, the card won't look as good (with "x" and number right next to each other). The downside to showing "x" on hover is, it's less discoverable. If this becomes an issue, we could show a help bubble the first time you add a card.

**Comment by mbookman** [comment]
SGTM
